default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:482174993053:android:ea550aafa70250cf3b8a74",
      firebase_cli_token: "1//03ojcxN-nzDLeCgYIARAAGAMSNwF-L9Irt8jT16JgMwtyUTHLZTdHylhJqRHvPGpw9Jykq3B8lKLvFOGXxA5jUDK9LRoUb32x9P4",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mido81347@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end